import { CServerMain } from "../../../../artgine/network/CServerMain.js";
import { CBoardServer } from "../../../../artgine/server/CBoardServer.js";
import { COAuthServer } from "../../../../artgine/server/COAuthServer.js";
import { CSingServer } from "../../../../artgine/server/CSingServer.js";
import { CVillageWorld } from "./CVillageWorld.js";
new CBoardServer().SetServerMain(CServerMain.Main());
new CSingServer().SetServerMain(CServerMain.Main());
new COAuthServer().SetServerMain(CServerMain.Main());
let zoneServer = new CVillageWorld();
zoneServer.SetServerMain(CServerMain.Main());
zoneServer.UpdateLoop();
