import "https://06fs4dix.github.io/Artgine/artgine/artgine.js";
import { CPreferences } from "https://06fs4dix.github.io/Artgine/artgine/basic/CPreferences.js";
var gPF = new CPreferences();
gPF.mTargetWidth = 0;
gPF.mTargetHeight = 0;
gPF.mRenderer = "GL";
gPF.m32fDepth = false;
gPF.mTexture16f = false;
gPF.mAnti = true;
gPF.mBatchPool = true;
gPF.mXR = false;
gPF.mDeveloper = true;
gPF.mIAuto = true;
gPF.mWASM = false;
gPF.mCanvas = "";
gPF.mServer = 'webServer';
gPF.mGitHub = false;
gPF.mVersion = "mpy1x7kf_2";
import { CAtelier } from "https://06fs4dix.github.io/Artgine/artgine/app/CAtelier.js";
import { CPlugin } from "https://06fs4dix.github.io/Artgine/artgine/util/CPlugin.js";
CPlugin.PushPath('ShadowPlane', '../../../Artgine/plugin/ShadowPlane/');
import "../../../Artgine/plugin/ShadowPlane/ShadowPlane.js";
CPlugin.PushPath('Water', '../../../Artgine/plugin/Water/');
import "../../../Artgine/plugin/Water/Water.js";
var gAtl = new CAtelier();
gAtl.mPF = gPF;
await gAtl.Init(['Main.json'], "");
var Main = gAtl.Canvas('Main.json');
import { CAlert } from "https://06fs4dix.github.io/Artgine/artgine/basic/CAlert.js";
CAlert.Info("f3로 개발모드에서 라이팅 위치와 값을 수정해 보세요", 60 * 1000);
