import "../../../artgine/artgine.js";
import { CPreferences } from "../../../artgine/basic/CPreferences.js";
var gPF = new CPreferences();
gPF.mTargetWidth = 0;
gPF.mTargetHeight = 0;
gPF.mRenderer = "GL";
gPF.m32fDepth = false;
gPF.mTexture16f = false;
gPF.mAnti = true;
gPF.mBatchPool = true;
gPF.mXR = false;
gPF.mDeveloper = true;
gPF.mIAuto = true;
gPF.mWASM = false;
gPF.mCanvas = "";
gPF.mServer = 'local';
gPF.mGitHub = false;
gPF.mVersion = "mpuhzq22_17";
import { CAtelier } from "../../../artgine/app/CAtelier.js";
var gAtl = new CAtelier();
gAtl.mPF = gPF;
await gAtl.Init([], "");
import { CCamCon3DFirstPerson } from "../../../artgine/util/CCamCon.js";
import { CRenderPass } from "../../../artgine/render/CRenderPass.js";
import { CSubject } from "../../../artgine/app/subject/CSubject.js";
import { CPaint3D } from "../../../artgine/app/component/paint/CPaint3D.js";
import { CParticle, CParticleShapeOut } from "../../../artgine/app/subject/CParticle.js";
import { CPaint2D } from "../../../artgine/app/component/paint/CPaint2D.js";
import { CColor } from "../../../artgine/render/CColor.js";
import { CVec3 } from "../../../artgine/geometry/CVec3.js";
import { CVec2 } from "../../../artgine/geometry/CVec2.js";
import { CAlpha } from "../../../artgine/render/CAlpha.js";
import { CAnimation, CClipAlpha, CClipColor, CClipDestroy, CClipPRS } from "../../../artgine/app/component/CAnimation.js";
import { CAniFlow } from "../../../artgine/app/component/CAniFlow.js";
import { CSampList } from "../../../artgine/util/CSampler.js";
import { CEvent } from "../../../artgine/basic/CEvent.js";
import { CInput } from "../../../artgine/system/CInput.js";
import { CPool } from "../../../artgine/basic/CPool.js";
import { CTrail } from "../../../artgine/app/subject/CTrail.js";
var Main = gAtl.NewCanvas("Main");
Main.SetCameraKey("3D");
gAtl.Brush().GetCam3D().SetCamCon(new CCamCon3DFirstPerson(gAtl.Frame().Input()));
var obj = new CSubject();
var pt = new CPaint3D(gAtl.Frame().Pal().GetBoxMesh());
let rp = new CRenderPass(gAtl.Frame().Pal().Sl3DKey());
rp.SetPriority(CRenderPass.ePriority.BackGround);
pt.PushRenderPass(rp);
pt.SetTexture(gAtl.Frame().Pal().GetNoneTex());
obj.PushComp(pt);
obj.SetSca(new CVec3(10, 0.1, 10));
Main.PushSub(obj);
var particle = new CParticle();
var sub0 = new CSubject();
CPool.On("Type0", () => {
    let psub0 = new CSubject();
    let ptbill = new CPaint2D(gAtl.Frame().Pal().GetNoneTex(), new CVec2(100, 100));
    ptbill.SetBillBoard(true);
    ptbill.SetColorModel(new CColor(0, 1, 0, CColor.eModel.RGBMul));
    psub0.PushComp(ptbill);
    var ani = new CAnimation();
    ani.Push(new CClipAlpha(0, 5, new CAlpha(1), new CAlpha(0)));
    ani.Push(new CClipDestroy(5));
    psub0.PushComp(new CAniFlow(ani));
    return psub0;
}, CPool.ePool.Product);
CPool.On("Type0", (_r) => {
}, CPool.ePool.Recycle);
let ptbill = new CPaint2D(gAtl.Frame().Pal().GetNoneTex(), new CVec2(100, 100));
ptbill.SetBillBoard(true);
ptbill.SetColorModel(new CColor(0, 1, 0, CColor.eModel.RGBMul));
sub0.PushComp(ptbill);
var ani = new CAnimation();
ani.Push(new CClipAlpha(0, 5, new CAlpha(1), new CAlpha(0)));
ani.Push(new CClipDestroy(5));
sub0.PushComp(new CAniFlow(ani));
var sub1 = new CSubject();
ptbill = new CPaint2D(gAtl.Frame().Pal().GetNoneTex(), new CVec2(10, 100));
ptbill.SetColorModel(new CColor(1, 0, 0, CColor.eModel.RGBMul));
ptbill.SetBillBoard(true);
ptbill.Tail();
sub1.PushComp(ptbill);
var ani = new CAnimation();
ani.Push(new CClipColor(5, 10, new CColor(0, 0, 0, CColor.eModel.RGBAdd), new CColor(1, -1, -1, CColor.eModel.RGBAdd)));
ani.Push(new CClipDestroy(10));
sub1.PushComp(new CAniFlow(ani));
var sub2 = new CSubject();
ptbill = new CPaint2D(gAtl.Frame().Pal().GetNoneTex(), new CVec2(100, 100));
ptbill.SetColorModel(new CColor(0, 0, 1, CColor.eModel.RGBMul));
sub2.PushComp(ptbill);
var ani = new CAnimation();
ani.Push(new CClipDestroy(5));
sub2.PushComp(new CAniFlow(ani));
var sam = new CSampList([sub0, sub1, sub2], [1, 4, 2]);
particle.mSample = sam;
particle.mShape = new CParticleShapeOut();
Main.PushSub(particle);
var trail3Obj = Main.PushSub(new CTrail(gAtl.Brush().GetCam3D()));
trail3Obj.mLength = 1000;
trail3Obj.mFadeTime = 10.0;
var ani = new CAnimation();
ani.Push(new CClipPRS(0, 5, new CVec3(500, 100, 500), new CVec3(500, 100, -500), 0));
ani.Push(new CClipPRS(5, 5, new CVec3(500, 100, -500), new CVec3(-500, 100, -500), 0));
ani.Push(new CClipPRS(10, 5, new CVec3(-500, 100, -500), new CVec3(-500, 100, 500), 0));
ani.Push(new CClipPRS(15, 5, new CVec3(-500, 100, 500), new CVec3(500, 100, 500), 0));
trail3Obj.PushComp(new CAniFlow(ani));
function SwordThrustTrail(distance = 400, size = 50, duration = 0.3, center = new CVec3(0, 100, 0), direction = new CVec3(0, 0, 1)) {
    const tip = new CVec3(center.x + direction.x * distance, center.y + direction.y * distance, center.z + direction.z * distance);
    const trail = new CTrail(gAtl.Brush().GetCam3D());
    Main.PushSub(trail);
    const thrustAni = new CAnimation();
    thrustAni.Push(new CClipPRS(0, duration, center, tip, 0));
    thrustAni.Push(new CClipPRS(duration, duration, tip, center, 0));
    thrustAni.mLoop = false;
    let af = trail.PushComp(new CAniFlow(thrustAni));
    return trail;
}
function SwordCircleTrail(radius = 300, size = 50, duration = 1.5, center = new CVec3(0, 100, 0)) {
    const SEGMENTS = 32;
    const segDur = duration / SEGMENTS;
    const trail = new CTrail(gAtl.Brush().GetCam3D());
    trail.mLastSmall = true;
    trail.mLastHide = false;
    Main.PushSub(trail);
    const swordAni = new CAnimation();
    for (let i = 0; i < SEGMENTS; i++) {
        const a0 = (i / SEGMENTS) * Math.PI * 2;
        const a1 = ((i + 1) / SEGMENTS) * Math.PI * 2;
        swordAni.Push(new CClipPRS(i * segDur, segDur, new CVec3(center.x + Math.cos(a0) * radius, center.y, center.z + Math.sin(a0) * radius), new CVec3(center.x + Math.cos(a1) * radius, center.y, center.z + Math.sin(a1) * radius), 0));
    }
    trail.PushComp(new CAniFlow(swordAni));
    const destroyTime = duration * 2 + 1.0;
    let elapsed = 0;
    const cleanupEv = new CEvent();
    cleanupEv.mEvent = (_dt) => {
        elapsed += _dt;
        if (elapsed >= destroyTime) {
            trail.Destroy();
            gAtl.Frame().RemoveEvent(cleanupEv);
        }
    };
    gAtl.Frame().PushEvent(CEvent.eType.Update, cleanupEv);
    return trail;
}
gAtl.Frame().PushEvent(CEvent.eType.Update, () => {
    const input = gAtl.Frame().Input();
    if (input.KeyDown(CInput.eKey.F, true)) {
        SwordThrustTrail(400, 50, 0.3, new CVec3(0, 100, 0), new CVec3(0, 0, 1));
    }
});
SwordCircleTrail(300, 50, 1.5, new CVec3(0, 100, 0));
