import "../../../Artgine/artgine/artgine.js";
import { CPreferences } from "../../../Artgine/artgine/basic/CPreferences.js";
var gPF = new CPreferences();
gPF.mTargetWidth = 0;
gPF.mTargetHeight = 0;
gPF.mRenderer = "GL";
gPF.m32fDepth = false;
gPF.mTexture16f = false;
gPF.mAnti = true;
gPF.mBatchPool = true;
gPF.mXR = false;
gPF.mDeveloper = true;
gPF.mIAuto = true;
gPF.mWASM = false;
gPF.mCanvas = "";
gPF.mServer = 'local';
gPF.mGitHub = false;
gPF.mVersion = "mpuhzq22_94";
import { CAtelier } from "../../../Artgine/artgine/app/CAtelier.js";
var gAtl = new CAtelier();
gAtl.mPF = gPF;
await gAtl.Init(['Main.json'], "");
var Main = gAtl.Canvas('Main.json');
import { CConfirm } from "../../../Artgine/artgine/basic/CModal.js";
import { CVec2 } from "../../../Artgine/artgine/geometry/CVec2.js";
import { CVoxelMap, CVTile } from "../../../Artgine/artgine/app/subject/CVoxelMap.js";
import { CCollider } from "../../../Artgine/artgine/app/component/CCollider.js";
import { CVec3 } from "../../../Artgine/artgine/geometry/CVec3.js";
import { CSampler } from "../../../Artgine/artgine/util/CSampler.js";
import { CDensityInfo2D, CDensityMap } from "../../../Artgine/artgine/app/subject/CDensityMap.js";
import { CCamCon2DFreeMove, CCamCon3DFirstPerson } from "../../../Artgine/artgine/util/CCamCon.js";
import { CBound } from "../../../Artgine/artgine/geometry/CBound.js";
import { CSubject } from "../../../Artgine/artgine/app/subject/CSubject.js";
import { CConsol } from "../../../Artgine/artgine/basic/CConsol.js";
import { CWind } from "../../../Artgine/artgine/app/component/CWind.js";
import { CUtil } from "../../../Artgine/artgine/basic/CUtil.js";
var gVoxel = new CVoxelMap();
gVoxel.SetBlackBoard(true);
Main.PushSub(gVoxel);
gAtl.Brush().GetCam2D().SetCamCon(new CCamCon2DFreeMove(gAtl.Frame().Input()));
gAtl.Brush().GetCam3D().SetCamCon(new CCamCon3DFirstPerson(gAtl.Frame().Input()));
CConfirm.List("Voxel Mode Select!", [
    async () => {
        await gAtl.Frame().Load().Exe("Res/tutorial_map_2d.png");
        await gVoxel.mAtlas.PushSizeCut("Res/TilesetFloor.png", new CVec2(16, 16));
        const N = CCollider.eEvent.None;
        let col = "";
        gVoxel.PushTile(new CVTile(0xff000000, 22, col, "땅0"));
        gVoxel.PushTile(new CVTile(0x10000000, 86, col, "땅1"));
        gVoxel.PushTile(new CVTile(0x20000000, 85, col, "땅2"));
        gVoxel.PushTile(new CVTile(0x00ff0000, 99, col, "어두운 땅0"));
        gVoxel.PushTile(new CVTile(0x00100000, 100, col, "어두운 땅1"));
        gVoxel.PushTile(new CVTile(0x00200000, 101, col, "어두운 땅2"));
        gVoxel.PushTile(new CVTile(0x00300000, 102, col, "어두운 땅3"));
        gVoxel.PushTile(new CVTile(0x00400000, 103, col, "어두운 땅4"));
        gVoxel.PushTile(new CVTile(0x0000ff00, 222, col, "풀0"));
        gVoxel.PushTile(new CVTile(0x00001000, 208, col, "풀1"));
        gVoxel.PushTile(new CVTile(0x00002000, 207, col, "풀2"));
        gVoxel.PushTile(new CVTile(0x00003000, 223, col, "풀3"));
        gVoxel.PushTile(new CVTile(0x00004000, 224, col, "풀4"));
        gVoxel.PushTile(new CVTile(0x00000f00, 275, col, "진흙0"));
        gVoxel.ResetInfo(new CVec3(256, 256, 1), 100);
        let tex = gAtl.Frame().Res().Find("Res/tutorial_map_2d.png");
        gVoxel.mBuf.SetTexture(tex);
        let densityMap = new CDensityMap();
        densityMap.mDiv = 10;
        densityMap.mBuf.Reset(new CVec3(256, 256, 1), 100);
        let info = densityMap.PushDensityInfo(new CDensityInfo2D(0x0000ff00, new CVec3(500, 500, 500), "Res/tutorial_map.png"));
        info.mSca = new CSampler(new CVec3(0.8, 0.8, 0.8));
        info.mColliderLayer = "density";
        info.mWind = 1;
        Main.PushSub(densityMap);
        densityMap.mBuf.SetTexture(tex);
        let sub = Main.PushSub(new CSubject());
        sub["Collision"] = () => {
            CConsol.Log("cl");
        };
        let cl = sub.PushComp(new CCollider());
        cl.SetLayer("test");
        cl.PushCollisionLayer("density");
        cl.PushCollisionLayer("voxel");
        let bound = new CBound();
        bound.InitBound(50);
        bound.SetType(CBound.eType.Box);
        cl.InitBound(bound);
        let windSub = Main.PushSub(new CSubject());
        windSub.SetKey("Wind");
        let wind = windSub.PushComp(new CWind());
        let testbuf = new Uint8Array(32);
        testbuf.fill(1);
        let str = CUtil.ArrayToLZBase64(testbuf.buffer);
        let test = new Uint8Array(CUtil.LZBase64ToArray(str));
        CConsol.Log(test);
    },
    async () => {
        gAtl.Brush().GetCam3D().SetFar(5000);
        Main.SetCameraKey("3D");
        gVoxel.mAtlas.mPadding = 8;
        await gAtl.Frame().Load().Exe("Res/tutorial_map_3d.png");
        await gVoxel.mAtlas.Push("Res/floor/tutorial_pad.png");
        await gVoxel.mAtlas.Push("Res/floor/pedestal_full.png");
        await gVoxel.mAtlas.Push("Res/floor/dirt0.png");
        await gVoxel.mAtlas.Push("Res/floor/floor_sand_stone0.png");
        await gVoxel.mAtlas.Push("Res/water/dngn_shoals_shallow_water1.png");
        gVoxel.PushTile(new CVTile(0xFF000000, 1, "voxel"));
        gVoxel.PushTile(new CVTile(0xAA884400, 2, "voxel"));
        gVoxel.PushTile(new CVTile(0x88552200, 3, "voxel"));
        gVoxel.PushTile(new CVTile(0xCCBB8800, 4, "voxel"));
        gVoxel.PushTile(new CVTile(0x2266CC00, 5, "voxel"));
        let tex = gAtl.Frame().Res().Find("Res/tutorial_map_3d.png");
        gVoxel.ResetInfo(new CVec3(128, 8, 128), 100);
        gVoxel.mBuf.GetBuf().fill(0xFF000000);
        gVoxel.mBuf.SetTexture(tex);
    }
], ["2D", "3D"]);
