import "../../../Artgine/artgine/artgine.js";
import { CClass } from "../../../Artgine/artgine/basic/CClass.js";
import { CNPC } from "./CNPC.js";
CClass.Push(CNPC);
import { CUser } from "./CUser.js";
CClass.Push(CUser);
import { CPreferences } from "../../../Artgine/artgine/basic/CPreferences.js";
var gPF = new CPreferences();
gPF.mTargetWidth = 0;
gPF.mTargetHeight = 0;
gPF.mRenderer = "GL";
gPF.m32fDepth = false;
gPF.mTexture16f = false;
gPF.mAnti = true;
gPF.mBatchPool = true;
gPF.mXR = false;
gPF.mDeveloper = true;
gPF.mIAuto = true;
gPF.mWASM = false;
gPF.mCanvas = "";
gPF.mServer = 'local';
gPF.mGitHub = false;
gPF.mVersion = "mq9kph7i_5";
import { CAtelier } from "../../../Artgine/artgine/app/CAtelier.js";
import { CPlugin } from "../../../Artgine/artgine/util/CPlugin.js";
CPlugin.PushPath('Inventory', '../../../Artgine/plugin/Inventory/');
import "../../../Artgine/plugin/Inventory/Inventory.js";
CPlugin.PushPath('ShadowPlane', '../../../Artgine/plugin/ShadowPlane/');
import "../../../Artgine/plugin/ShadowPlane/ShadowPlane.js";
CPlugin.PushPath('Water', '../../../Artgine/plugin/Water/');
import "../../../Artgine/plugin/Water/Water.js";
var gAtl = new CAtelier();
gAtl.mPF = gPF;
await gAtl.Init(['Main.json', 'Real.json'], "");
var Main = gAtl.Canvas('Main.json');
var Real = gAtl.Canvas('Real.json');
let comcon = gAtl.Brush().GetCam2D().SetCamCon(new CCamCon2DFollow(gAtl.Frame().Input()));
gAtl.Brush().GetCam2D().Set2DZoom(1.5);
import { CVec3 } from "../../../Artgine/artgine/geometry/CVec3.js";
import { CBlackBoard } from "../../../Artgine/artgine/basic/CBlackBoard.js";
import { CBlackboardModal, CMDViewer, CModalBackGround } from "../../../Artgine/artgine/util/CModalUtil.js";
import { CModal, CModalTitleBar } from "../../../Artgine/artgine/basic/CModal.js";
import { CVec4 } from "../../../Artgine/artgine/geometry/CVec4.js";
import { CTexture, CTextureInfo } from "../../../Artgine/artgine/render/CTexture.js";
import { CCamCon2DFollow } from "../../../Artgine/artgine/util/CCamCon.js";
import { CSysAuth } from "../../../Artgine/artgine/system/CSysAuth.js";
import { CAudioTag } from "../../../Artgine/artgine/system/audio/CAudio.js";
import { CDOM } from "../../../Artgine/artgine/basic/CDOM.js";
import { CShaderAttr } from "../../../Artgine/artgine/render/CShaderAttr.js";
import { CSurfaceBloom } from "../../../Artgine/plugin/Bloom/Bloom.js";
import { CRenderPass } from "../../../Artgine/artgine/render/CRenderPass.js";
import { CSubject } from "../../../Artgine/artgine/app/subject/CSubject.js";
import { CCanvasPluginRPMgr } from "../../../Artgine/artgine/app/canvas/CCanvasPluginRPMgr.js";
import { CRPAuto, CRPMgr } from "../../../Artgine/artgine/app/canvas/CRPMgr.js";
import { CCondition } from "../../../Artgine/artgine/util/CCondition.js";
import { CSurface } from "../../../Artgine/artgine/app/subject/CSurface.js";
import { CLight } from "../../../Artgine/artgine/app/component/CLight.js";
import { CPad } from "../../../Artgine/artgine/app/subject/CPad.js";
import { CMat } from "../../../Artgine/artgine/geometry/CMat.js";
import { Bootstrap } from "../../../Artgine/artgine/basic/Bootstrap.js";
import { CHTMLDropdown } from "../../../Artgine/artgine/util/CHTMLBar.js";
import { CDensityInfo2D, CDensityMap } from "../../../Artgine/artgine/app/subject/CDensityMap.js";
import { CBound } from "../../../Artgine/artgine/geometry/CBound.js";
import { CSampler, CSampMinMax } from "../../../Artgine/artgine/util/CSampler.js";
import { CPaint } from "../../../Artgine/artgine/app/component/paint/CPaint.js";
import { CLoaderOption } from "../../../Artgine/artgine/util/CLoader.js";
{
    const backVoxel = Main.Find("BackGround");
    if (backVoxel) {
        const densityMap = Real.PushSub(new CDensityMap());
        densityMap.mBuf = backVoxel.mBuf;
        densityMap.mDiv = 10;
        const tex = "Res/Back/TilesetNature.png";
        gAtl.Frame().Load().Exe(tex, new CLoaderOption().Set("mFilter", CTexture.eFilter.Neaest));
        const ltree = densityMap.PushDensityInfo(new CDensityInfo2D(0x0000ff00, new CVec3(800, 800, 0), tex, new CSampler(new CVec4(0.12447916716337204, 0.14226190745830536, 0.12526041269302368, 0.000297616352327168))));
        ltree.mYSort = true;
        ltree.mWind = 20;
        ltree.mSca = new CSampler(new CVec3(0.375, 0.375, 1));
        ltree.mPos = new CSampMinMax(new CVec3(-300, -300, 0), new CVec3(300, 300, 0));
        ltree.mColliderLayer = "object";
        ltree.mBound = new CBound();
        ltree.mBound.SetType(CBound.eType.Box);
        ltree.mBound.mMin.Import(new CVec3(-50 / 300, -120 / 300, -0.5));
        ltree.mBound.mMax.Import(new CVec3(50 / 300, -50 / 300, 0.5));
        ltree.mPaintTag.push(CPaint.eTag.Shadow);
        const mtree = densityMap.PushDensityInfo(new CDensityInfo2D(0x00001000, new CVec3(600, 600, 0), tex, new CSampler(new CVec4(0.08020833134651184, 0.09166666865348816, 0.0002604166802484542, 0.9080356955528259))));
        mtree.mYSort = true;
        mtree.mWind = 20;
        mtree.mSca = new CSampler(new CVec3(0.167, 0.167, 1));
        mtree.mPos = new CSampMinMax(new CVec3(-250, -250, 0), new CVec3(250, 250, 0));
        mtree.mColliderLayer = "object";
        mtree.mBound = new CBound();
        mtree.mBound.SetType(CBound.eType.Box);
        mtree.mBound.mMin.Import(new CVec3(-50 / 100, -30 / 100, -0.5));
        mtree.mBound.mMax.Import(new CVec3(50 / 100, 0 / 100, 0.5));
        mtree.mPaintTag.push(CPaint.eTag.Shadow);
        const flower1 = densityMap.PushDensityInfo(new CDensityInfo2D(0x00002000, new CVec3(400, 400, 0), tex, new CSampler(new CVec4(0.04114583507180214, 0.04702381044626236, 0.04192708432674408, 0.4288690388202667))));
        flower1.mYSort = true;
        flower1.mWind = 50;
        flower1.mSca = new CSampler(new CVec3(0.125, 0.125, 1));
        flower1.mPos = new CSampMinMax(new CVec3(-150, -150, 0), new CVec3(150, 150, 0));
        flower1.mPaintTag.push(CPaint.eTag.Shadow);
        const flower2 = densityMap.PushDensityInfo(new CDensityInfo2D(0x00003000, new CVec3(400, 400, 0), tex, new CSampler(new CVec4(0.03593749925494194, 0.04404762014746666, 0.12786458432674408, 0.4288690388202667))));
        flower2.mYSort = true;
        flower2.mWind = 50;
        flower2.mSca = new CSampler(new CVec3(0.125, 0.125, 1));
        flower2.mPos = new CSampMinMax(new CVec3(-150, -150, 0), new CVec3(150, 150, 0));
        flower2.mPaintTag.push(CPaint.eTag.Shadow);
    }
}
CModal.PushTitleBar(new CModalTitleBar("DevToolModal", "Unit", async () => {
    let ba = [];
    for (let [key, value] of CBlackBoard.Map()) {
        if (value instanceof CSubject) {
            ba.push(key);
        }
    }
    new CBlackboardModal(ba);
}));
Real.PushSub(new CNPC("Dante")).SetPos(new CVec3(6600, 6400));
Real.PushSub(new CNPC("Miles")).SetPos(new CVec3(6200, 9200));
Real.PushSub(new CNPC("Poppy")).SetPos(new CVec3(11000, 8000));
let rpPlug = new CCanvasPluginRPMgr(null);
Real.PushPlugin(rpPlug);
let AM7RP = new CRPMgr();
let rp = AM7RP.PushRP(new CRPAuto());
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2D" }));
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2DMerge" }));
rp.PushAnd(new CCondition({ "s": "mTag[shadowPlane]", "v": 0 }));
rp.mShader = gAtl.Frame().Pal().Sl2DKey();
rp.mTag.add("light");
rp = AM7RP.PushRP(new CRPAuto());
rp.PushAnd(new CCondition({ "s": "class", "v": "CPaintVoxel" }));
rp.mShader = gAtl.Frame().Pal().SlVoxelKey();
rp.mTag.add("light");
let PM1RP = new CRPMgr();
rp = PM1RP.PushRP(new CRPAuto());
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2D" }));
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2DMerge" }));
rp.PushAnd(new CCondition({ "s": "mTag[shadowPlane]", "v": 0 }));
rp.mShader = gAtl.Frame().Pal().Sl2DKey();
rp = PM1RP.PushRP(new CRPAuto());
rp.PushAnd(new CCondition({ "s": "class", "v": "CPaintVoxel" }));
rp.mShader = gAtl.Frame().Pal().SlVoxelKey();
rpPlug.SetRPMgr(PM1RP);
let PM11RP = new CRPMgr();
let emissiveTex = new CTexture();
emissiveTex.PushInfo([new CTextureInfo(CTexture.eTarget.Sigle, CTexture.eFormat.RGBA8, 1)]);
let emissiveTexKey = PM11RP.PushTex("Bloom/emissiveTex.tex", emissiveTex);
rp = PM11RP.PushRP(new CRPAuto());
rp.PushAnd(new CCondition({ "s": "class", "v": "CPaint2D" }));
rp.PushAnd(new CCondition({ "s": "mTag[bloom]" }));
rp.mShader = gAtl.Frame().Pal().Sl2DKey();
rp.mRenderTarget = emissiveTexKey;
rp.mTag.add("mask");
rp = PM11RP.PushRP(new CRPAuto());
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2D" }));
rp.PushOr(new CCondition({ "s": "class", "v": "CPaint2DMerge" }));
rp.PushAnd(new CCondition({ "s": "mTag[shadowPlane]", "v": 0 }));
rp.mShader = gAtl.Frame().Pal().Sl2DKey();
rp.mTag.add("light");
rp = PM11RP.PushRP(new CRPAuto());
rp.PushAnd(new CCondition({ "s": "class", "v": "CPaintVoxel" }));
rp.mShader = gAtl.Frame().Pal().SlVoxelKey();
rp.mTag.add("light");
rp = PM11RP.PushRP(new CRPAuto());
rp.PushAnd(new CCondition({ "s": "class", "v": "CShadowPlane" }));
rp.PushAnd(new CCondition({ "s": "mTag[shadowPlane]" }));
rp.mShader = gAtl.Frame().Pal().Sl2DKey();
let sufBloom = PM11RP.PushSuf(new CSurfaceBloom());
let srp = sufBloom.GetRP();
srp.mShader = gAtl.Frame().Pal().Sl2DKey();
srp.mTag.add("blit");
srp.mShaderAttr.push(new CShaderAttr(0, emissiveTexKey));
sufBloom.OldSchool();
sufBloom.m_threshold = 1.0;
sufBloom.m_softThreshold = 1.0;
let sufLast = PM11RP.PushSuf(new CSurface());
srp = sufLast.GetRP();
srp.mRenderTarget = gAtl.Frame().Pal().GetDefaultFrameBuffer();
srp.mShader = gAtl.Frame().Pal().SlPostKey();
srp.mTag.add("blend");
srp.mShaderAttr.push(new CShaderAttr(0, gAtl.Frame().Pal().GetMainFrameTex()));
srp.mShaderAttr.push(new CShaderAttr(1, sufBloom.GetTexKey()));
srp.mShaderAttr.push(new CShaderAttr("TexOffBlendFactor", new CMat([1, 1, CRenderPass.eBlend.LinearDodge])));
function AM7() {
    rpPlug.SetRPMgr(AM7RP);
    let Direct = Main.Find("Direct");
    let PointList = Main.Find("PointList");
    let dirLight = Direct.FindComp(CLight);
    Direct.SetPos(new CVec3(1, 1, 0));
    PointList.SetEnable(false);
}
window["AM7"] = AM7;
function PM1() {
    rpPlug.SetRPMgr(PM1RP);
    let Direct = Main.Find("Direct");
    let PointList = Main.Find("PointList");
    let dirLight = Direct.FindComp(CLight);
    Direct.SetPos(new CVec3(0, 1, 0));
    PointList.SetEnable(false);
}
window["PM1"] = PM1;
function PM11() {
    rpPlug.SetRPMgr(PM11RP);
    let Direct = Main.Find("Direct");
    let PointList = Main.Find("PointList");
    Direct.SetPos(new CVec3(1, 0, 0));
    PointList.SetEnable(true);
}
window["PM11"] = PM11;
PM1();
let audioEnable = await CSysAuth.Confirm(true);
if (audioEnable) {
    let audio = new CAudioTag("Res/sound/TownTheme.mp3");
    audio.Volume(0.5);
    audio.Play();
}
new CMDViewer("README.md");
let user = Real.PushSub(new CUser());
user.SetPos(new CVec3(5200, 6500));
user.PushChild(new CPad()).mSave = false;
let mg = new CModalBackGround("barRoot");
let arr = [];
arr.push(new CHTMLDropdown("root", "OptionBar", "Option", Bootstrap.eColor.warning));
arr.push(new CHTMLDropdown("OptionBar", "OptionAM7", `<div onclick="AM7()">AM7</div>`, Bootstrap.eColor.light));
arr.push(new CHTMLDropdown("OptionBar", "OptionPM1", `<div onclick="PM1()">PM1</div>`, Bootstrap.eColor.light));
arr.push(new CHTMLDropdown("OptionBar", "OptionPM11", `<div onclick="PM11()">PM11</div>`, Bootstrap.eColor.light));
const dummy = CHTMLDropdown.Attach(arr, "left");
let rightDiv = CDOM.DataToDom(`<div class="position-fixed top-0 end-0" style="z-index:2000;"></div>`);
rightDiv.append(dummy);
mg.SetBody(rightDiv);
